name: Auto Open PR (docs branch)

on:
  push:
    branches:
      - chore/docs-badges-and-env-example
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-pr-${{ github.ref }}
  cancel-in-progress: false

jobs:
  open-pr:
    name: Open PR to main if missing
    runs-on: ubuntu-latest
    env:
      PR_BRANCH: chore/docs-badges-and-env-example
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Tip if you want to use a PAT instead
        run: |
          echo "If this step fails with 'not permitted to create or approve pull requests', you can either:"
          echo "  1) Enable the repo setting: Actions > General > 'Allow GitHub Actions to create and approve pull requests'"
          echo "  2) Add a fine-scoped PAT secret named PAT_CREATE_PR and switch this job to use it (see workflow comments)"

      - name: Ensure a tiny diff to guarantee PR creation
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          mkdir -p .github/ci
          date +%s > .github/ci/auto-pr-trigger.txt
          git add -A
          git commit -m "chore(ci): ensure diff for auto-PR workflow" || true

      - name: Create PR (peter-evans/create-pull-request)
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.PR_BRANCH }}
          base: main
          title: 'chore(docs): add CI badges and clarify .env.example'
          body: |
            Adds CI badges (CodeQL, ZAP) to README and clarifies .env.example for ZAP/Pact local usage.
            This PR exists to trigger CodeQL analysis on pull_request.
          maintainer-can-modify: true
          draft: false
