name: Auto Open PR (docs branch)

on:
  push:
    branches:
      - chore/docs-badges-and-env-example
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-pr-${{ github.ref }}
  cancel-in-progress: false

jobs:
  open-pr:
    name: Open PR to main if missing
    runs-on: ubuntu-latest
    env:
      PR_BRANCH: chore/docs-badges-and-env-example
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tip if you want to use a PAT instead
        run: |
          echo "If this step fails with 'not permitted to create or approve pull requests', you can either:"
          echo "  1) Enable the repo setting: Actions > General > 'Allow GitHub Actions to create and approve pull requests'"
          echo "  2) Add a fine-scoped PAT secret named PAT_CREATE_PR and switch this job to use it (see workflow comments)"

      - name: Ensure a tiny diff to guarantee PR creation
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          mkdir -p .github/ci
          date +%s > .github/ci/auto-pr-trigger.txt
          git add -A
          git commit -m "chore(ci): ensure diff for auto-PR workflow" || true

      - name: Open PR via GitHub REST API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BASE: main
          HEAD: ${{ env.PR_BRANCH }}
          TITLE: 'chore(docs): add CI badges and clarify .env.example'
        run: |
          set -e
          echo "Checking for existing open PR from ${HEAD} to ${BASE}..."
          EXISTING=$(curl -sS -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" \
            "${{ github.api_url }}/repos/${REPO}/pulls?head=${{ github.repository_owner }}:${HEAD}&base=${BASE}&state=open")
          COUNT=$(echo "$EXISTING" | jq 'length')
          if [ "$COUNT" -gt 0 ]; then
            echo "Open PR already exists. Skipping creation."; exit 0;
          fi
          echo "No existing PR found. Creating a new one..."
          BODY=$'Adds CI badges (CodeQL, ZAP) to README and clarifies .env.example for ZAP/Pact local usage.\nThis PR exists to trigger CodeQL analysis on pull_request.'
          CREATE=$(jq -nc --arg title "$TITLE" --arg head "$HEAD" --arg base "$BASE" --arg body "$BODY" '{title:$title, head:$head, base:$base, body:$body, maintainer_can_modify:true, draft:false}')
          RESP=$(curl -sS -X POST -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" \
            -d "$CREATE" "${{ github.api_url }}/repos/${REPO}/pulls")
          URL=$(echo "$RESP" | jq -r '.html_url // empty')
          if [ -n "$URL" ]; then
            echo "PR created: $URL"
          else
            echo "PR creation response:" && echo "$RESP"
            echo "Failed to create PR" >&2; exit 1;
          fi
