name: Nightly Test Suite

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for testing'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      include_performance:
        description: 'Include performance tests'
        required: true
        default: true
        type: boolean
      include_security:
        description: 'Include security tests'
        required: true
        default: true
        type: boolean

env:
  NODE_VERSION: '18'
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.cache/ms-playwright

jobs:
  nightly-full-suite:
    name: Nightly Full Test Suite
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        environment: [staging]
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
      - name: Cache Playwright browsers
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps

      - name: Run comprehensive UI tests
        run: |
          npm run test:ui:comprehensive -- --project=${{ matrix.browser }}
        env:
          TEST_ENV: ${{ matrix.environment }}
          BROWSER: ${{ matrix.browser }}
          CI: true
          NIGHTLY: true

      - name: Upload Playwright traces on failure
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: traces-nightly-${{ matrix.browser }}
          path: |
            test-results/
            reports/test-execution/**/playwright-report/
          retention-days: 14

      - name: Run API regression tests
        run: |
          npm run test:api:regression
        env:
          TEST_ENV: ${{ matrix.environment }}
          CI: true

      - name: Run accessibility tests
        run: |
          npm run test:accessibility
        env:
          CI: true

      - name: Upload nightly test results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: always()
        with:
          name: nightly-results-${{ matrix.browser }}-${{ matrix.environment }}
          path: |
            reports/
            test-results/
            playwright-report/
          retention-days: 14

  performance-tests:
    name: Nightly Performance Tests
    runs-on: ubuntu-latest
    if: github.event.inputs.include_performance != 'false'
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: Cache Playwright browsers
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Setup JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz
          tar -xzf apache-jmeter-5.6.2.tgz
          echo "${{ github.workspace }}/apache-jmeter-5.6.2/bin" >> $GITHUB_PATH

      - name: Install k6 (Debian/Ubuntu)
        run: |
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run k6 load (SLO-gated)
        run: |
          mkdir -p reports/load-tests/k6
          npm run test:load:k6:load
        env:
          CI: true
          JMETER_HOME: ${{ github.workspace }}/apache-jmeter-5.6.2
          TEST_ENV: ${{ github.event.inputs.environment || 'staging' }}
          BASE_URL: https://www.saucedemo.com

      - name: Aggregate k6 JUnit results
        if: always()
        run: |
          npm run report:k6:junit:aggregate || true
        shell: bash

      - name: Run JMeter performance (SLO-gated)
        run: |
          node automated-tests/performance-tests/scripts/jmeter-runner.js --users 50 --ramp-up 60 --loops 3
        env:
          CI: true

      - name: Upload performance results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: always()
        with:
          name: nightly-performance-results
          path: |
            reports/performance-tests/
            reports/load-tests/
            automated-tests/performance-tests/jmeter/results/
          retention-days: 14

  security-tests:
    name: Nightly Security Tests
    runs-on: ubuntu-latest
    if: github.event.inputs.include_security != 'false'
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
      - name: Cache Playwright browsers
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps

      - name: Run security tests
        run: |
          npm run test:security:comprehensive
        env:
          CI: true
          TEST_ENV: ${{ github.event.inputs.environment || 'staging' }}

      - name: Upload security results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: always()
        with:
          name: nightly-security-results
          path: |
            reports/security-tests/
            test-results/
          retention-days: 14

  generate-nightly-report:
    name: Generate Nightly Report
    runs-on: ubuntu-latest
    needs: [nightly-full-suite, performance-tests, security-tests]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download all artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          path: nightly-artifacts/

      - name: Generate consolidated nightly report
        run: |
          echo "📊 Generating nightly test report..."
          npm run report:nightly
        env:
          CI: true

      - name: Upload consolidated nightly report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: always()
        with:
          name: nightly-consolidated-report
          path: |
            reports/nightly/
            nightly-artifacts/
          retention-days: 30

      - name: Send notification on failure
        if: failure()
        run: |
          echo "🚨 Nightly test suite failed!"
          echo "Check the workflow logs for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          # Here you would integrate with notification systems like Slack, email, etc.
