name: ZAP Baseline Scan

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target URL to scan'
        required: false
        default: 'https://magento.softwaretestingboard.com'
  schedule:
    - cron: '0 4 * * 1' # Mondays at 04:00 UTC

permissions:
  contents: read
  issues: write

jobs:
  zap-scan:
    name: Baseline scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@7c4deb10e6261301961c86d65d54a516394f9aed
        with:
          target: 'https://www.saucedemo.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          issue_title: 'ZAP Baseline Scan Report'
          artifact_name: 'zap_scan'
