name: ZAP Baseline Scan

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target URL to scan'
        required: false
        default: 'https://magento.softwaretestingboard.com'
  schedule:
    - cron: '0 4 * * 1' # Mondays at 04:00 UTC

permissions:
  contents: read
  issues: write

jobs:
  zap-scan:
    name: Baseline scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ github.event.inputs.target || 'https://magento.softwaretestingboard.com' }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          cmd_options: '-a'
          allow_issue_writing: true
          issue_title: 'ZAP Baseline Scan Report'
          artifact_name: 'zap_scan'
